#!/bin/bash
head -n -1 翻譯研究/試驗結果.txt | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音.txt 
echo 斷字
${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt < 基準/moses試驗結果斷字.txt 
echo 原本斷詞組：
sed 's/\-/ /g' 基準/moses試驗結果.txt | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt
#sed 's/\-/ /g' 基準/moses試驗結果.txt | head
