#!/bin/bash
echo 斷詞
cat 翻譯研究/試驗結果斷詞.txt | sed 's/\-/ /g' | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt
cat 基準/moses試驗結果斷詞.txt  | sed 's/\-/ /g' | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt
${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷詞.txt < 基準/moses試驗結果斷詞.txt 
echo 國語斷詞
cat 翻譯研究/試驗結果國語斷詞.txt | sed 's/\-/ /g' | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt
${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt < 基準/moses試驗結果國語斷詞.txt 
echo 斷字
${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt < 基準/moses試驗結果斷字.txt 
echo 原本斷詞組：
cat 翻譯研究/試驗結果.txt | sed 's/\-/ /g' | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt
cat 基準/moses試驗結果.txt  | sed 's/\-/ /g' | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音斷字.txt
${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc 語料/試.閩南語音.txt < 基準/moses試驗結果.txt 
