#!/bin/bash
num=00
name=${num}.斷詞
src_type=${num}.斷詞
trg_type=${num}.斷詞

source 公家指令

set_var

zcat ../語料/華臺華語字斷詞.txt.gz  | python3 ../資料處理/編碼.py > ${src_text}
zcat ../語料/華臺一對一斷詞組.txt.gz  | python3 ../資料處理/編碼.py > ${trg_text}
cp ${trg_text} ${lm_text}
zcat ../語料/附錄句一對一斷詞.txt.gz ../語料/臺語文數位典藏一對一.txt.gz  | python3 ../資料處理/編碼.py >> ${lm_text}
zcat ../語料/例句華語字斷詞.txt.gz  > ${test_text}
zcat ../語料/例句一對一.txt.gz  > ${ans_text}

prepare_data
make_model
