#!/bin/bash
zcat ../語料/試.例句國語字斷字.txt.gz > ../斷詞斷字比較/試.例句華語字斷字.txt
zcat ../語料/試.例句國語字斷詞.txt.gz > ../斷詞斷字比較/試.例句華語字斷詞.txt
declare -i port=8001
for i in 華斷字_閩斷字 華斷詞_閩斷字 華斷字_閩斷詞 華斷詞_閩斷詞
do
	echo $i $port
	PYTHONPATH=..:../../tai5_uan5_gian5_gi2_kang1_ku7/ python3 ../翻譯研究/對摩西翻譯改通用.py 試驗結果_${i} $i $port & 
	port=$port+1
done
