#!/bin/bash
zcat ../語料/例句一對一.txt.gz | PYTHONPATH=..:../../tai5_uan5_gian5_gi2_kang1_ku7/ python3 ../資料處理/斷一對一字.py > ../斷詞斷字比較/例句一對一斷字.txt
zcat ../語料/例句一對一.txt.gz > ../斷詞斷字比較/例句一對一斷詞.txt

for i in 華斷字_閩斷字 華斷詞_閩斷字 華斷字_閩斷詞 華斷詞_閩斷詞
do
	echo $i
	for j in 攏無配 配斷字 配斷詞
	do
		cat 試驗結果_${j}_${i} | PYTHONPATH=..:../../tai5_uan5_gian5_gi2_kang1_ku7/ python3 ../資料處理/斷一對一字.py | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc ../斷詞斷字比較/例句一對一斷字.txt
	done
	
	echo $i 斷詞直接比較
	for j in 攏無配 配斷字 配斷詞
	do
		cat 試驗結果_斷詞_${j}_${i} |  ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc ../斷詞斷字比較/例句一對一斷詞.txt
	done
	
	echo $i 重斷詞比較
	for j in 攏無配 配斷字 配斷詞
	do
		cat 試驗結果_${j}_${i} | PYTHONPATH=..:../../tai5_uan5_gian5_gi2_kang1_ku7/ python3 ../資料處理/斷一對一字.py | ${SCRIPTS_ROOTDIR}/generic/multi-bleu.perl -lc ../斷詞斷字比較/例句一對一斷詞.txt
	done
done