#!/bin/bash
ngram-count -order 3 -interpolate -kndiscount -unk -text ../語料/訓.閩南語音斷字.txt -lm 閩南語音斷字.txt.lm
$SCRIPTS_ROOTDIR/training/train-model.perl -root-dir 國語斷詞 -corpus ${HOME}/git/huan1-ik8_gian5-kiu3/基準/../語料/訓 -f 國語字斷詞.txt -e 閩南語音斷字.txt -alignment grow-diag-final-and -reordering msd-bidirectional-fe -lm 0:3:${HOME}/git/huan1-ik8_gian5-kiu3/基準/閩南語音斷字.txt.lm -external-bin-dir=${HOME}/mt/
moses -f 國語斷詞/model/moses.ini  < ../語料/試.國語字斷詞.txt > moses試驗結果國語斷詞.txt
