#!/bin/bash
name=國語斷詞
src=國語斷詞文本.txt
trg=閩南語斷字文本.txt
lm_text=閩南語斷字模型.txt
test_text=斷詞試驗文本.txt
result_text=moses試驗結果斷字.txt

src_text=${name}.${src}
trg_text=${name}.${trg}

#予斷字、斷詞、斷詞組處理中央的代誌
#ln -s  ${src_text}
#ln -s  ${trg_text}

$SCRIPTS_ROOTDIR/training/train-model.perl -root-dir ${name} -corpus ${HOME}/git/huan1-ik8_gian5-kiu3/基準/${name} -f ${src} -e ${trg} -alignment grow-diag-final-and -reordering msd-bidirectional-fe -lm 0:3:${HOME}/git/huan1-ik8_gian5-kiu3/基準/${lm_text}.lm -external-bin-dir=${HOME}/mt/
moses -f work/model/moses.ini < ${test_text} > ${result_text}
