#!/bin/bash
name=國語斷詞
src_type=斷詞
trg_type=斷字

src=${src_type}.國語文本.txt
trg=${trg_type}.閩南語文本.txt
lm_text=${trg_type}.閩南語模型.txt
test_text=${src_type}.試驗文本.txt
result_text=moses${name}試驗結果.txt

#予斷字、斷詞、斷詞組處理中央的代誌

$SCRIPTS_ROOTDIR/training/train-model.perl -root-dir ${name} -corpus ${HOME}/git/huan1-ik8_gian5-kiu3/基準/訓 -f ${src} -e ${trg} -alignment grow-diag-final-and -reordering msd-bidirectional-fe -lm 0:3:${HOME}/git/huan1-ik8_gian5-kiu3/基準/${lm_text}.lm -external-bin-dir=${HOME}/mt/
moses -f ${name}/model/moses.ini < ${test_text} > ${result_text}
