#!/bin/bash
ngram-count -order 3 -interpolate -kndiscount -unk -text ../語料/訓.閩南語音.txt -lm 閩南語音.txt.lm
$SCRIPTS_ROOTDIR/training/train-model.perl -root-dir work -corpus ${HOME}/git/huan1-ik8_gian5-kiu3/基準/../語料/訓 -f 國語字.txt -e 閩南語音.txt -alignment grow-diag-final-and -reordering msd-bidirectional-fe -lm 0:3:${HOME}/git/huan1-ik8_gian5-kiu3/基準/閩南語音.txt.lm -external-bin-dir=${HOME}/mt/
moses -f work/model/moses.ini  < ../語料/試.國語字.txt > moses試驗結果.txt
