#!/bin/bash
name=斷字
src_type=斷字
trg_type=斷字

source 公家指令

set_var

cat ../語料/訓.華臺國語字斷字.txt | native2ascii > ${src_text}
zcat ../語料/訓.例句國語字斷字.txt.gz | native2ascii >> ${src_text}
zcat ../語料/訓.華臺一對一斷字.txt.gz ../語料/訓.例句一對一斷字.txt.gz | native2ascii > ${trg_text}
cat ${trg_text} | native2ascii > ${lm_text}
zcat ../語料/附錄句一對一斷字.txt.gz | native2ascii >> ${lm_text}
cat ../語料/試.華臺國語字斷字.txt | native2ascii > ${test_text}
zcat ../語料/試.例句國語字斷字.txt.gz | native2ascii >> ${test_text}
zcat ../語料/試.華臺一對一斷字.txt.gz ../語料/試.例句一對一斷字.txt.gz | native2ascii > ${ans_text}

prepare_data
make_model