#!/bin/bash
#$1 名
#$2 國語
#$3 閩南語
#bash -x 通用指令 閩南語斷詞 國語字斷字 閩南語音斷詞

ngram-count -order 3 -interpolate -kndiscount -unk -text ../語料/訓.$3.txt -lm $3.txt.lm
$SCRIPTS_ROOTDIR/training/train-model.perl -root-dir $1 -corpus ${HOME}/git/huan1-ik8_gian5-kiu3/基準/../語料/訓 -f $2.txt -e $3.txt -alignment grow-diag-final-and -reordering msd-bidirectional-fe -lm 0:3:${HOME}/git/huan1-ik8_gian5-kiu3/基準/$3.txt.lm -external-bin-dir=${HOME}/mt/
moses -f $1/model/moses.ini  < ../語料/試.$2.txt > moses試驗結果$3.txt
#bash -x 通用指令 閩南語斷詞 國語字斷字 閩南語音斷詞
#bash -x 通用指令 國語斷詞組 國語字 閩南語音斷字
#bash -x 通用指令 閩南語斷詞組 國語字斷字 閩南語音
#bash -x 通用指令 國語斷詞組閩南語斷詞 國語字 閩南語音斷詞
#bash -x 通用指令 國語斷詞閩南語斷詞組 國語字斷詞 閩南語音

